#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 16 15:33:12 2023

@author: MyBlipe
"""

import pandas as pd
import matplotlib as plt
from sklearn.linear_model import LinearRegression

auto = pd.read_csv('auto-mpg.csv') 
print(auto.shape)


X = auto.iloc[:, 1:-1] # wybierz kolumny od drugiej do przedostatniej
X = X.drop('horsepower', axis=1) # usuń kolumnę 'horsepower'
    
y = auto.loc[:,'mpg']

X.head()
y.head()

    # tworzymy model
lr = LinearRegression()
lr.fit(X.to_numpy(), y)
lr.score(X.to_numpy(), y)

    # dwa fikcyjne pojazdy
my_car1 = [4, 160, 190, 12, 90, 1]
my_car2 = [4, 200, 260, 15, 83, 1]
     
cars = [my_car1, my_car2]


mpg = lr.predict(cars)
print(mpg)
